### PR TITLE
added innodb_file_per_table option

### PR DESCRIPTION
**Pull request by phendryx**

### CODE REVIEW

**Comment by needo37** [comment]
This looks good. What is the technical benefit of this?

**Comment by phendryx** [comment]
This is specific to the InnoDB engine. if you create 5 databases, each with 5 tables, and put 1 gig of data in each table, you would end up with a single ibdata file in your /db directory that is 25gb in size. With this option enabled, it will create a directory per database and a set of files in that directory per table.  In addition to that, if you do not use this option and you delete one of the databases in this example, you can not reclaim the 5 gb of disk space, you can only reuse it with another database.

**Comment by phendryx** [comment]
BTW- I'm asshopo from the unRaid forums ;)

**Comment by needo37** [comment]
Makes sense! Approved!

**Pull request merged**
